### ISSUE TITLE
Review apps are always created in us-east-1 region

### ISSUE THREAD

**Issue by dolohow** [nagelflorian/terraform-aws-s3-review-apps#26]
Hi,

I have a configuration that has
```
region = "eu-central-1"
```

However, all resources are created in `us-east-1`.

Thanks for your work, it saves a lot of time :)

**Comment by nagelflorian** [comment]
Thanks for reporting. I'm going to look into this in the next couple of days.

**Comment by nagelflorian** [comment]
@dolohow Sorry it took me this long to respond to your issue.

Have you seen my comment to your question on the related lines (https://github.com/nagelflorian/terraform-aws-s3-review-apps/commit/dd69bbdebfdfa2ba4f1061d6da5b1d6df8050e12#r61463901)? I believe CloudFront Lambda Functions are still restricted to be only created in `us-east-1`. You can also see this by running the e2e tests for your changes and setting the region to a different one:

```
error creating CloudFront Distribution: InvalidLambdaFunctionAssociation: The function must be in region 'us-east-1'
```

Unfortunately, this means your changes won't work as they are right now as long as AWS CloudFront doesn't remove this restriction.
